import { useEffect, useState } from 'react'
import { PencilLine, Plus, Trash2 } from 'lucide-react'
import { supabase } from './lib/supabase'

type Sport = { id: string; week_number: number; day_of_week: number; title: string; description: string; duration_minutes: number | null; program: string; session_name: string; warmup: string; main_workout: string; cooldown: string; equipment: string }
type Form = Omit<Sport, 'id'>
const days = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche']
const emptyForm: Form = { week_number: 1, day_of_week: 1, title: '', description: '', duration_minutes: 45, program: 'Musculation', session_name: '', warmup: '', main_workout: '', cooldown: '', equipment: '' }

export default function AdminSportManager() {
  const [items, setItems] = useState<Sport[]>([])
  const [form, setForm] = useState<Form>(emptyForm)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [open, setOpen] = useState(false)
  const [message, setMessage] = useState('')
  async function load() { const { data } = await supabase.from('weekly_schedule_items').select('id, week_number, day_of_week, title, description, duration_minutes, workout_sessions(program, session_name, warmup, main_workout, cooldown, equipment)').eq('category', 'sport').order('week_number').order('day_of_week'); const rows = (data ?? []) as Array<Sport & { workout_sessions: Sport | Sport[] | null }>; setItems(rows.map((row) => { const workout = Array.isArray(row.workout_sessions) ? row.workout_sessions[0] : row.workout_sessions; return { ...row, program: workout?.program ?? 'Musculation', session_name: workout?.session_name ?? row.title, warmup: workout?.warmup ?? '', main_workout: workout?.main_workout ?? '', cooldown: workout?.cooldown ?? '', equipment: workout?.equipment ?? '' } })) }
  useEffect(() => { void load() }, [])
  function reset() { setEditingId(null); setForm(emptyForm); setMessage('') }
  function edit(item: Sport) { setEditingId(item.id); setForm({ week_number: item.week_number, day_of_week: item.day_of_week, title: item.title, description: item.description, duration_minutes: item.duration_minutes, program: item.program, session_name: item.session_name, warmup: item.warmup, main_workout: item.main_workout, cooldown: item.cooldown, equipment: item.equipment }); setOpen(true); setMessage('') }
  async function save(event: React.FormEvent) { event.preventDefault(); const schedulePayload = { category: 'sport', week_number: Number(form.week_number), day_of_week: Number(form.day_of_week), title: form.title.trim(), description: form.description.trim(), duration_minutes: form.duration_minutes ? Number(form.duration_minutes) : null }; const scheduleResult = editingId ? await supabase.from('weekly_schedule_items').update(schedulePayload).eq('id', editingId) : await supabase.from('weekly_schedule_items').insert(schedulePayload).select('id').single(); if (scheduleResult.error) { setMessage(scheduleResult.error.message); return }; const id = editingId ?? (scheduleResult.data as { id: string }).id; const workoutResult = await supabase.from('workout_sessions').upsert({ schedule_item_id: id, program: form.program.trim(), session_name: form.session_name.trim() || form.title.trim(), warmup: form.warmup.trim(), main_workout: form.main_workout.trim(), cooldown: form.cooldown.trim(), equipment: form.equipment.trim() }, { onConflict: 'schedule_item_id' }); if (workoutResult.error) { setMessage(workoutResult.error.message); return }; reset(); setOpen(false); await load() }
  async function remove(id: string) { const { error } = await supabase.from('weekly_schedule_items').delete().eq('id', id); if (error) setMessage(error.message); else await load() }
  const update = (key: keyof Form, value: string | number | null) => setForm((current) => ({ ...current, [key]: value }))
  return <section className="library-admin sport-admin"><div className="library-admin-heading"><div><p className="card-kicker">Administration · sport</p><h3>Gérer les programmes d’entraînement</h3><p className="muted">Ajoute, modifie ou supprime les programmes affichés dans Plan & Plate.</p></div><button className="primary-button" type="button" onClick={() => { reset(); setOpen(true) }}><Plus size={15} /> Ajouter</button></div>{open && <form className="library-admin-form" onSubmit={(event) => void save(event)}><div className="library-form-grid"><label>Semaine<input type="number" min={1} max={16} value={form.week_number} onChange={(event) => update('week_number', Number(event.target.value))} /></label><label>Jour<select value={form.day_of_week} onChange={(event) => update('day_of_week', Number(event.target.value))}>{days.map((day, index) => <option value={index + 1} key={day}>{day}</option>)}</select></label><label>Durée (min)<input type="number" min={1} value={form.duration_minutes ?? ''} onChange={(event) => update('duration_minutes', Number(event.target.value))} /></label></div><label>Programme<input value={form.program} onChange={(event) => update('program', event.target.value)} required /></label><label>Titre de la séance<input value={form.title} onChange={(event) => update('title', event.target.value)} required /></label><label>Description<textarea rows={3} value={form.description} onChange={(event) => update('description', event.target.value)} /></label><label>Échauffement<textarea rows={3} value={form.warmup} onChange={(event) => update('warmup', event.target.value)} /></label><label>Bloc principal<textarea rows={5} value={form.main_workout} onChange={(event) => update('main_workout', event.target.value)} /></label><label>Retour au calme<textarea rows={3} value={form.cooldown} onChange={(event) => update('cooldown', event.target.value)} /></label><label>Matériel<input value={form.equipment} onChange={(event) => update('equipment', event.target.value)} /></label>{message && <p className="form-error">{message}</p>}<div className="recap-actions"><button className="primary-button" type="submit">{editingId ? 'Mettre à jour' : 'Enregistrer'}</button><button className="secondary-button" type="button" onClick={() => { reset(); setOpen(false) }}>Annuler</button></div></form>}<div className="library-admin-list">{items.map((item) => <div className="library-admin-row" key={item.id}><div><strong>{item.program} · {item.title}</strong><small>Semaine {item.week_number} · {days[item.day_of_week - 1]} · {item.duration_minutes ?? '—'} min</small></div><button className="inline-action" type="button" onClick={() => edit(item)}><PencilLine size={14} /> Modifier</button><button className="inline-action danger" type="button" onClick={() => void remove(item.id)}><Trash2 size={14} /> Supprimer</button></div>)}</div></section>
}
