import { useEffect, useState } from 'react'
import { ArrowLeft, BookOpen, CheckCircle2, CirclePlay, Dumbbell, Leaf, Mic, Volume2 } from 'lucide-react'
import { supabase } from './lib/supabase'

type Activity = { id: string; category: 'language' | 'sport' | 'food'; title: string; description: string; duration_minutes: number | null; language?: string | null }
type Course = { title: string; summary: string; theory: string; examples: string; level: string | null }
type Props = { activity: Activity | null; onBack: () => void }

export default function CourseHub({ activity, onBack }: Props) {
  const [course, setCourse] = useState<Course | null>(null)
  const [answer, setAnswer] = useState('')
  const [validated, setValidated] = useState(false)
  const [loading, setLoading] = useState(false)
  useEffect(() => {
    async function loadCourse() {
      if (!activity || activity.category !== 'language') return
      setLoading(true)
      const { data } = await supabase.from('language_courses').select('title, summary, theory, examples, level').eq('language', activity.title).order('course_number').limit(1).maybeSingle()
      setCourse((data as Course | null) ?? { title: `Cours de ${activity.title}`, summary: activity.description || `Session guidée de ${activity.title}.`, theory: `Cette séance de ${activity.title} développe le vocabulaire, la compréhension et la production autour d’un thème concret.`, examples: `Bonjour. · Comment allez-vous ? · Je pratique ${activity.title} chaque semaine.`, level: null })
      setLoading(false)
    }
    void loadCourse()
    setAnswer(''); setValidated(false)
  }, [activity])
  if (!activity) return <section className="hub-empty"><BookOpen size={22} /><h2>Votre hub de cours</h2><p className="muted">Sélectionnez une activité dans le planning pour ouvrir son contenu.</p></section>
  const icon = activity.category === 'language' ? <BookOpen /> : activity.category === 'sport' ? <Dumbbell /> : <Leaf />
  const label = activity.category === 'language' ? 'Cours de langue' : activity.category === 'sport' ? 'Séance sportive' : 'Nutrition & recette'
  return <section className="course-hub"><button className="back-link" onClick={onBack}><ArrowLeft size={16} /> Retour au planning</button><div className="hub-hero"><span className={`hub-icon ${activity.category}`}>{icon}</span><div><p className="eyebrow">{label}</p><h2>{course?.title ?? activity.title}</h2><p className="muted">{activity.duration_minutes ? `${activity.duration_minutes} minutes · ` : ''}{activity.description || 'Un module pratique pour votre parcours.'}</p></div></div>{loading ? <p className="loading-state">Chargement du cours...</p> : activity.category === 'language' && course ? <LanguageLesson course={course} answer={answer} setAnswer={setAnswer} validated={validated} setValidated={setValidated} /> : activity.category === 'sport' ? <SportLesson activity={activity} validated={validated} setValidated={setValidated} /> : <FoodLesson activity={activity} validated={validated} setValidated={setValidated} />}</section>
}

function LanguageLesson({ course, answer, setAnswer, validated, setValidated }: { course: Course; answer: string; setAnswer: (value: string) => void; validated: boolean; setValidated: (value: boolean) => void }) { return <div className="lesson-grid"><article className="lesson-card"><p className="card-kicker">Théorie</p><h3>{course.summary || 'L’essentiel de la séance'}</h3><p>{course.theory}</p></article><article className="lesson-card"><p className="card-kicker">Exemples</p><div className="examples">{course.examples.split('·').map((example) => <p key={example}>{example.trim()}</p>)}</div><button className="lesson-action" onClick={() => window.speechSynthesis.speak(new SpeechSynthesisUtterance(course.examples))}><Volume2 size={16} /> Écouter les exemples</button></article><article className="exercise-card"><div className="exercise-heading"><span className="exercise-number">01</span><div><p className="card-kicker">Exercice écrit</p><h3>Complétez la phrase</h3></div></div><p>Écrivez une phrase simple avec le vocabulaire de la séance.</p><input value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Votre réponse..." /><button className="primary-button" onClick={() => setValidated(true)}>{validated ? <><CheckCircle2 size={16} /> Réponse enregistrée</> : 'Valider ma réponse'}</button></article><article className="exercise-card oral"><div className="exercise-heading"><span className="exercise-number">02</span><div><p className="card-kicker">Exercice oral</p><h3>Répétez à voix haute</h3></div></div><p>Écoutez la phrase puis entraînez votre prononciation.</p><div className="oral-controls"><button className="lesson-action" onClick={() => window.speechSynthesis.speak(new SpeechSynthesisUtterance(course.examples.split('·')[0]))}><Volume2 size={16} /> Écouter</button><button className="lesson-action" onClick={() => setValidated(true)}><Mic size={16} /> J’ai répété</button></div></article></div> }
function SportLesson({ activity, validated, setValidated }: { activity: Activity; validated: boolean; setValidated: (value: boolean) => void }) { return <div className="lesson-grid"><article className="lesson-card"><p className="card-kicker">Objectif de la séance</p><h3>{activity.title}</h3><p>{activity.description || 'Une séance progressive adaptée à votre semaine.'}</p><ul className="lesson-list"><li>Échauffement · 8 min</li><li>Bloc principal · {activity.duration_minutes ? `${Math.max(activity.duration_minutes - 13, 10)} min` : '30 min'}</li><li>Retour au calme · 5 min</li></ul></article><article className="exercise-card"><div className="exercise-heading"><CirclePlay size={19} /><div><p className="card-kicker">Suivi de séance</p><h3>Prêt à commencer ?</h3></div></div><p>Cochez la séance lorsque vous l’avez terminée pour alimenter votre suivi.</p><button className="primary-button" onClick={() => setValidated(!validated)}>{validated ? <><CheckCircle2 size={16} /> Séance terminée</> : 'Marquer comme terminée'}</button></article></div> }
function FoodLesson({ activity, validated, setValidated }: { activity: Activity; validated: boolean; setValidated: (value: boolean) => void }) { return <div className="lesson-grid"><article className="lesson-card"><p className="card-kicker">Repas du jour</p><h3>{activity.title}</h3><p>{activity.description || 'Une proposition simple pour équilibrer votre journée.'}</p><ul className="lesson-list"><li>Préparer les ingrédients</li><li>Composer une assiette colorée</li><li>Boire un grand verre d’eau</li></ul></article><article className="exercise-card"><div className="exercise-heading"><Leaf size={19} /><div><p className="card-kicker">Rituel nutrition</p><h3>Préparation effectuée ?</h3></div></div><p>Validez votre repas pour garder une trace de votre régularité.</p><button className="primary-button" onClick={() => setValidated(!validated)}>{validated ? <><CheckCircle2 size={16} /> Repas validé</> : 'Valider le repas'}</button></article></div> }
