import { useEffect, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { PencilLine, Plus, Trash2 } from 'lucide-react'
import { supabase } from './lib/supabase'

type VisualizationType = 'line' | 'bar' | 'table'
type Metric = 'sport_weight' | 'sport_completed' | 'nutrition_rate' | 'nutrition_planned' | 'nutrition_completed' | 'language_score'
type Visualization = { id: string; title: string; visualization_type: VisualizationType; metric: Metric; position: number }
type Point = { date: string; value: number; label?: string }
type Props = { userId: string; sport: Point[]; nutrition: Point[]; language: Point[]; onChanged: () => void }
type Form = { title: string; visualization_type: VisualizationType; metric: Metric; position: number }
const metricLabels: Record<Metric, string> = { sport_weight: 'Sport · charge / poids', sport_completed: 'Sport · séances terminées', nutrition_rate: 'Nourriture · taux de repas réalisés', nutrition_planned: 'Nourriture · repas planifiés', nutrition_completed: 'Nourriture · repas réalisés', language_score: 'Cours · score de langue' }
const emptyForm: Form = { title: '', visualization_type: 'line', metric: 'sport_weight', position: 1 }

export default function ProgressVisualizations({ userId, sport, nutrition, language, onChanged }: Props) {
  const [items, setItems] = useState<Visualization[]>([])
  const [form, setForm] = useState<Form>(emptyForm)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [open, setOpen] = useState(false)
  const [message, setMessage] = useState('')
  async function load() { const { data } = await supabase.from('progress_visualizations').select('id, title, visualization_type, metric, position').eq('user_id', userId).order('position'); setItems((data ?? []) as Visualization[]) }
  useEffect(() => { void load() }, [userId])
  function reset() { setEditingId(null); setForm({ ...emptyForm, position: items.length + 1 }); setMessage('') }
  function edit(item: Visualization) { setEditingId(item.id); setForm({ title: item.title, visualization_type: item.visualization_type, metric: item.metric, position: item.position }); setOpen(true); setMessage('') }
  async function save(event: React.FormEvent) { event.preventDefault(); const payload = { user_id: userId, title: form.title.trim(), visualization_type: form.visualization_type, metric: form.metric, position: Number(form.position) || 1 }; const result = editingId ? await supabase.from('progress_visualizations').update(payload).eq('id', editingId) : await supabase.from('progress_visualizations').insert(payload); if (result.error) { setMessage(result.error.message); return }; reset(); setOpen(false); await load(); onChanged() }
  async function remove(id: string) { const { error } = await supabase.from('progress_visualizations').delete().eq('id', id); if (error) setMessage(error.message); else { await load(); onChanged() } }
  const series = (metric: Metric) => metric === 'sport_weight' || metric === 'sport_completed' ? sport : metric === 'language_score' ? language : nutrition
  return <section className="progress-visualizations"><div className="progress-visualizations-heading"><div><p className="card-kicker">Mesures personnalisées</p><h3>Ajouter des courbes, barres ou tableaux</h3><p className="muted">Choisis une donnée mesurable dans le sport, les cours ou la nourriture.</p></div><button className="primary-button" type="button" onClick={() => { reset(); setOpen(true) }}><Plus size={15} /> Ajouter une vue</button></div>{open && <form className="library-admin-form" onSubmit={(event) => void save(event)}><label>Nom de la vue<input value={form.title} onChange={(event) => setForm((current) => ({ ...current, title: event.target.value }))} placeholder="Ex. Régularité sportive" required /></label><div className="library-form-grid"><label>Type<select value={form.visualization_type} onChange={(event) => setForm((current) => ({ ...current, visualization_type: event.target.value as VisualizationType }))}><option value="line">Courbe</option><option value="bar">Barres</option><option value="table">Tableau</option></select></label><label>Mesure<select value={form.metric} onChange={(event) => setForm((current) => ({ ...current, metric: event.target.value as Metric }))}>{Object.entries(metricLabels).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label>Position<input type="number" min={1} value={form.position} onChange={(event) => setForm((current) => ({ ...current, position: Number(event.target.value) || 1 }))} /></label></div>{message && <p className="form-error">{message}</p>}<div className="recap-actions"><button className="primary-button" type="submit">{editingId ? 'Mettre à jour' : 'Enregistrer'}</button><button className="secondary-button" type="button" onClick={() => { reset(); setOpen(false) }}>Annuler</button></div></form>}<div className="progress-custom-grid">{items.map((item) => <article className="chart-card" key={item.id}><div className="chart-title"><div><p className="card-kicker">{item.visualization_type === 'line' ? 'Courbe' : item.visualization_type === 'bar' ? 'Barres' : 'Tableau'}</p><strong>{item.title}</strong></div><div className="content-block-actions"><button className="inline-action" type="button" onClick={() => edit(item)}><PencilLine size={14} /></button><button className="inline-action danger" type="button" onClick={() => void remove(item.id)}><Trash2 size={14} /></button></div></div><VisualizationView type={item.visualization_type} data={series(item.metric)} /></article>)}</div></section>
}

function VisualizationView({ type, data }: { type: VisualizationType; data: Point[] }) { if (!data.length) return <div className="chart-empty">Ajoute des données pour afficher cette vue.</div>; if (type === 'table') return <div className="progress-table-wrap"><table className="progress-table"><thead><tr><th>Date</th><th>Valeur</th></tr></thead><tbody>{data.map((point, index) => <tr key={`${point.date}-${index}`}><td>{point.date}</td><td>{point.value}</td></tr>)}</tbody></table></div>; return <ResponsiveContainer width="100%" height={190}>{type === 'bar' ? <BarChart data={data}><CartesianGrid stroke="#e3e4dc" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="value" fill="#527ba0" radius={[4, 4, 0, 0]} /></BarChart> : <LineChart data={data}><CartesianGrid stroke="#e3e4dc" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Line type="monotone" dataKey="value" stroke="#1f4d43" strokeWidth={3} dot={{ r: 3 }} /></LineChart>}</ResponsiveContainer> }
